# -*- coding: utf-8 -*-
"""CelsiusinFahrenheit_V1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11h-t6SpjjvNuBH5GlZKYX5Wm7slZxDkY
"""

Celsius = float(input("Value in Celsius:"))
  
Fahrenheit = 9*Celsius/5 + 32

Valor = Fahrenheit
print('Value in Fahrenheit:', Valor,"ºC")